services:
  - type: web
    name: youtube-watch-party
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 10000
